theme: jekyll-theme-cayman
name: Alex Batson

description: This website will, hopefully, provide me with a more creative outlet for expressing what I find interesting. I have not decided the purpose of this webiste, but I am interested in recording my thoughts while learning a bit of webdesign.
